services:
  api:
    build:
      context: .
      dockerfile: docker/api.dockerfile
    ports:
    - "8000:8000"
    - "5678:5678"
    volumes:
      - .:/home/app/api
    environment:
      - API_DATABASES__POSTGRES_URI=postgresql+asyncpg://postgres:postgres@postgres:5432/medical
    depends_on:
      - postgres
    stdin_open: true
    tty: true

  test:
    build:
      context: .
      dockerfile: docker/api_test.dockerfile
    ports:
    - "8001:8000"
    volumes:
      - .:/home/app/api
    environment:
      - API_DATABASES__POSTGRES_URI=postgresql+asyncpg://postgres:postgres@postgres:5432/medical_test
      - API_ENV = testing
    depends_on:
      - postgres
    stdin_open: true
    tty: true

  postgres:
    build:
      context: .
      dockerfile: docker/postgres.dockerfile
    ports:
    - "5432:5432"
    volumes:
      - $HOME/.postgres/medical/data/postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_DBS=medical, medical_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres