[default]
DEBUG = true
LOG_LEVEL = "TRACE"
API_V1_PREFIX = "/api/v1"

[default.databases]
postgres_uri = ""

[default.security]
TOKEN_URL = "/api/v1/token"
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 5
REFRESH_TOKEN_EXPIRE_MINUTES = 1440