"""rename_hashed_password_to_password

Revision ID: 7910ea212366
Revises: 4ba3bb48b7df
Create Date: 2024-06-04 22:39:39.461493

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7910ea212366'
down_revision: Union[str, None] = '4ba3bb48b7df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('user', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'user', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
