"""add doctor appointment and patient tables

Revision ID: aca7a906c87c
Revises: f9a075aca5a0
Create Date: 2024-06-09 12:52:30.761520

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'aca7a906c87c'
down_revision: Union[str, None] = 'f9a075aca5a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'doctor',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('crm', sa.VARCHAR(length=255), nullable=False),
        sa.Column('specialty', sa.VARCHAR(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['user.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_doctor_crm'), 'doctor', ['crm'], unique=False)
    op.create_index(op.f('ix_doctor_specialty'), 'doctor', ['specialty'], unique=False)
    op.create_index(op.f('ix_doctor_user_id'), 'doctor', ['user_id'], unique=False)
    op.create_table(
        'patient',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('cpf', sa.VARCHAR(length=11), nullable=False),
        sa.Column('sus_card', sa.VARCHAR(length=15), nullable=False),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['user.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('cpf'),
        sa.UniqueConstraint('sus_card'),
    )
    op.create_index(op.f('ix_patient_user_id'), 'patient', ['user_id'], unique=False)
    op.create_table(
        'appointment',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('doctor_id', sa.Integer(), nullable=False),
        sa.Column('patient_id', sa.Integer(), nullable=False),
        sa.Column('reason', sa.VARCHAR(length=255), nullable=False),
        sa.Column('notes', sa.TEXT(), nullable=True),
        sa.Column('date', sa.DateTime(timezone=True), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ['doctor_id'],
            ['doctor.id'],
        ),
        sa.ForeignKeyConstraint(
            ['patient_id'],
            ['patient.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_appointment_date'), 'appointment', ['date'], unique=False)
    op.create_index(op.f('ix_appointment_doctor_id'), 'appointment', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_appointment_patient_id'), 'appointment', ['patient_id'], unique=False)
    op.create_index(op.f('ix_appointment_reason'), 'appointment', ['reason'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appointment_reason'), table_name='appointment')
    op.drop_index(op.f('ix_appointment_patient_id'), table_name='appointment')
    op.drop_index(op.f('ix_appointment_doctor_id'), table_name='appointment')
    op.drop_index(op.f('ix_appointment_date'), table_name='appointment')
    op.drop_table('appointment')
    op.drop_index(op.f('ix_patient_user_id'), table_name='patient')
    op.drop_table('patient')
    op.drop_index(op.f('ix_doctor_user_id'), table_name='doctor')
    op.drop_index(op.f('ix_doctor_specialty'), table_name='doctor')
    op.drop_index(op.f('ix_doctor_crm'), table_name='doctor')
    op.drop_table('doctor')
    # ### end Alembic commands ###
