"""add is deleted field to all tables

Revision ID: c1829d729063
Revises: aca7a906c87c
Create Date: 2024-06-12 10:18:34.477311

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c1829d729063'
down_revision: Union[str, None] = 'aca7a906c87c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.create_index(op.f('ix_address_is_deleted'), 'address', ['is_deleted'], unique=False)
    op.add_column('appointment', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.create_index(op.f('ix_appointment_is_deleted'), 'appointment', ['is_deleted'], unique=False)
    op.add_column('doctor', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.create_index(op.f('ix_doctor_is_deleted'), 'doctor', ['is_deleted'], unique=False)
    op.add_column('patient', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.create_index(op.f('ix_patient_is_deleted'), 'patient', ['is_deleted'], unique=False)
    op.add_column('user', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.create_index(op.f('ix_user_is_deleted'), 'user', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_is_deleted'), table_name='user')
    op.drop_column('user', 'is_deleted')
    op.drop_index(op.f('ix_patient_is_deleted'), table_name='patient')
    op.drop_column('patient', 'is_deleted')
    op.drop_index(op.f('ix_doctor_is_deleted'), table_name='doctor')
    op.drop_column('doctor', 'is_deleted')
    op.drop_index(op.f('ix_appointment_is_deleted'), table_name='appointment')
    op.drop_column('appointment', 'is_deleted')
    op.drop_index(op.f('ix_address_is_deleted'), table_name='address')
    op.drop_column('address', 'is_deleted')
    # ### end Alembic commands ###
